"""TaeKwon-Do ITF Knowledge Base.

All textual content here is sourced directly from the official Encyclopedia of
Taekwon-Do by General Choi Hong Hi (the "Condensed" full edition, 770 pages,
2010 print) supplied by the user. Pattern meanings, tenets, theory of power,
belt colors, the 24-pattern reasoning quote, and composition wording are
verbatim from that source.
"""

# ============================================================
# 24 OFFICIAL ITF TULS - VERBATIM MEANINGS FROM ENCYCLOPEDIA
# ============================================================
TULS = [
    {
        "id": "chon-ji", "order": 1, "name": "Chon-Ji", "korean": "천지",
        "level": "9th Kup (Yellow Stripe)", "movements": 19, "diagram": "+",
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Chon-Ji means literally 'the Heaven the Earth'. It is, in the Orient, interpreted as the creation of the world or the beginning of human history; therefore, it is the initial pattern played by the beginner. This pattern consists of two similar parts; one to represent the Heaven and the other the Earth.",
        "meaning_ro": "Chon-Ji înseamnă literal 'Cerul și Pământul'. În Orient este interpretat ca crearea lumii sau începutul istoriei umane; de aceea, este primul pattern executat de începător. Acest pattern constă din două părți similare; una reprezintă Cerul, iar cealaltă Pământul.",
        "youtube_query": "Chon Ji ITF tul pattern",
    },
    {
        "id": "dan-gun", "order": 2, "name": "Dan-Gun", "korean": "단군",
        "level": "8th Kup (Yellow Belt)", "movements": 21, "diagram": "I",
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Dan-Gun is named after the holy Dan-Gun, the legendary founder of Korea in the year of 2,333 B.C.",
        "meaning_ro": "Dan-Gun este numit după sfântul Dan-Gun, întemeietorul legendar al Coreei în anul 2.333 î.Hr.",
        "youtube_query": "Dan Gun ITF tul pattern",
    },
    {
        "id": "do-san", "order": 3, "name": "Do-San", "korean": "도산",
        "level": "7th Kup (Green Stripe)", "movements": 24,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Do-San is the pseudonym of the patriot Ahn Chang-Ho (1876-1938). The 24 movements represent his entire life which he devoted to furthering the education of Korea and its independence movement.",
        "meaning_ro": "Do-San este pseudonimul patriotului Ahn Chang-Ho (1876-1938). Cele 24 de mișcări reprezintă întreaga sa viață, pe care a dedicat-o promovării educației Coreei și mișcării sale de independență.",
        "youtube_query": "Do San ITF tul pattern",
    },
    {
        "id": "won-hyo", "order": 4, "name": "Won-Hyo", "korean": "원효",
        "level": "6th Kup (Green Belt)", "movements": 28,
        "ready_posture": "Close Ready Stance A",
        "meaning_en": "Won-Hyo was the noted monk who introduced Buddhism to the Silla Dynasty in the year of 686 A.D.",
        "meaning_ro": "Won-Hyo a fost călugărul renumit care a introdus Budismul în Dinastia Silla în anul 686 d.Hr.",
        "youtube_query": "Won Hyo ITF tul pattern",
    },
    {
        "id": "yul-gok", "order": 5, "name": "Yul-Gok", "korean": "율곡",
        "level": "5th Kup (Blue Stripe)", "movements": 38, "diagram": "土",
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Yul-Gok is the pseudonym of a great philosopher and scholar Yi I (1536-1584) nicknamed the 'Confucius of Korea'. The 38 movements of this pattern refer to his birthplace on 38° latitude and the diagram (±) represents 'scholar'.",
        "meaning_ro": "Yul-Gok este pseudonimul marelui filosof și învățat Yi I (1536-1584), supranumit 'Confucius al Coreei'. Cele 38 de mișcări se referă la locul său de naștere la latitudinea de 38°, iar diagrama (土) reprezintă 'cărturar'.",
        "youtube_query": "Yul Gok ITF tul pattern",
    },
    {
        "id": "joong-gun", "order": 6, "name": "Joong-Gun", "korean": "중근",
        "level": "4th Kup (Blue Belt)", "movements": 32,
        "ready_posture": "Close Ready Stance B",
        "meaning_en": "Joong-Gun is named after the patriot Ahn Joong-Gun who assassinated Hiro-Bumi Ito, the first Japanese governor-general of Korea, known as the man who played the leading part in the Korea-Japan merger. There are 32 movements in this pattern to represent Mr. Ahn's age when he was executed at Lui-Shung prison (1910).",
        "meaning_ro": "Joong-Gun este numit după patriotul Ahn Joong-Gun, care l-a asasinat pe Hiro-Bumi Ito, primul guvernator general japonez al Coreei, cunoscut ca omul care a jucat rolul principal în fuziunea Coreea-Japonia. Cele 32 de mișcări reprezintă vârsta domnului Ahn la momentul executării sale la închisoarea Lui-Shung (1910).",
        "youtube_query": "Joong Gun ITF tul pattern",
    },
    {
        "id": "toi-gye", "order": 7, "name": "Toi-Gye", "korean": "퇴계",
        "level": "3rd Kup (Red Stripe)", "movements": 37, "diagram": "土",
        "ready_posture": "Close Ready Stance B",
        "meaning_en": "Toi-Gye is the pen name of the noted scholar Yi Hwang (16th century), an authority on neo-Confucianism. The 37 movements of the pattern refer to his birthplace on 37° latitude, the diagram (±) represents 'scholar'.",
        "meaning_ro": "Toi-Gye este pseudonimul renumitului învățat Yi Hwang (secolul al XVI-lea), autoritate în neo-Confucianism. Cele 37 de mișcări se referă la locul său de naștere la latitudinea de 37°, iar diagrama (土) reprezintă 'cărturar'.",
        "youtube_query": "Toi Gye ITF tul pattern",
    },
    {
        "id": "hwa-rang", "order": 8, "name": "Hwa-Rang", "korean": "화랑",
        "level": "2nd Kup (Red Belt)", "movements": 29,
        "ready_posture": "Parallel Ready Stance with X-Back-Hand",
        "meaning_en": "Hwa-Rang is named after the Hwa-Rang youth group which originated in the Silla Dynasty in the early 7th century. The 29 movements refer to the 29th Infantry Division, where Taekwon-Do developed into maturity.",
        "meaning_ro": "Hwa-Rang este numit după grupul de tineri Hwa-Rang, apărut în Dinastia Silla la începutul secolului al VII-lea. Cele 29 de mișcări se referă la Divizia 29 de Infanterie, unde Taekwon-Do s-a dezvoltat la maturitate.",
        "youtube_query": "Hwa Rang ITF tul pattern",
    },
    {
        "id": "choong-moo", "order": 9, "name": "Choong-Moo", "korean": "충무",
        "level": "1st Kup (Black Stripe)", "movements": 30,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Choong-Moo was the name given to the great Admiral Yi Soon-Sin of the Lee Dynasty. He was reputed to have invented the first armoured battleship (Kobukson) in 1592, which is said to be the precursor of the present day submarine. The reason why this pattern ends with a left-hand attack is to symbolize his regrettable death, having no chance to show his unrestrained potentiality checked by the forced reservation of his loyalty to the king.",
        "meaning_ro": "Choong-Moo a fost numele dat marelui Amiral Yi Soon-Sin al Dinastiei Lee. Se spune că a inventat prima navă de luptă blindată (Kobukson) în 1592, despre care se spune că este precursorul submarinului modern. Motivul pentru care acest pattern se încheie cu un atac cu mâna stângă este de a simboliza moartea sa regretabilă, neavând șansa de a-și arăta potențialul neîngrădit, controlat de rezervarea forțată a loialității sale față de rege.",
        "youtube_query": "Choong Moo ITF tul pattern",
    },
    {
        "id": "kwang-gae", "order": 10, "name": "Kwang-Gae", "korean": "광개",
        "level": "1st Dan (Black Belt)", "movements": 39, "diagram": "I",
        "ready_posture": "Heaven Hand Ready Stance",
        "meaning_en": "Kwang-Gae is named after the famous Kwang-Gae-Toh-Wang, the 19th King of the Koguryo Dynasty, who regained all the lost territories including the greater part of Manchuria. The diagram represents the expansion and recovery of lost territory. The 39 movements refer to the first two figures of 391 A.D., the year he came to the throne.",
        "meaning_ro": "Kwang-Gae este numit după faimosul Kwang-Gae-Toh-Wang, al 19-lea Rege al Dinastiei Koguryo, care a recuperat toate teritoriile pierdute, inclusiv cea mai mare parte din Manciuria. Diagrama reprezintă expansiunea și recuperarea teritoriului pierdut. Cele 39 de mișcări se referă la primele două cifre ale anului 391 d.Hr., anul în care a urcat pe tron.",
        "youtube_query": "Kwang Gae ITF tul pattern",
    },
    {
        "id": "po-eun", "order": 11, "name": "Po-Eun", "korean": "포은",
        "level": "1st Dan (Black Belt)", "movements": 36, "diagram": "—",
        "ready_posture": "Parallel Ready Stance with Heaven Hand",
        "meaning_en": "Po-Eun is the pseudonym of a loyal subject Chong Mong-Chu (1400) who was a famous poet and whose poem 'I would not serve a second master though I might be crucified a hundred times' is known to every Korean. He was also a pioneer in the field of physics. The diagram (—) represents his unerring loyalty to the king and country towards the end of the Koryo Dynasty.",
        "meaning_ro": "Po-Eun este pseudonimul unui supus loial, Chong Mong-Chu (1400), poet faimos al cărui poem 'Nu aș sluji unui al doilea stăpân chiar dacă aș fi crucificat de o sută de ori' este cunoscut fiecărui coreean. A fost, de asemenea, un pionier în domeniul fizicii. Diagrama (—) reprezintă loialitatea sa neclintită față de rege și țară către sfârșitul Dinastiei Koryo.",
        "youtube_query": "Po Eun ITF tul pattern",
    },
    {
        "id": "ge-baek", "order": 12, "name": "Ge-Baek", "korean": "계백",
        "level": "1st Dan (Black Belt)", "movements": 44, "diagram": "I",
        "ready_posture": "Parallel Ready Stance with X-Back-Hand",
        "meaning_en": "Ge-Baek is named after Ge-Baek, a great general in the Baek Je Dynasty (660 A.D.). The diagram represents his severe and strict military discipline.",
        "meaning_ro": "Ge-Baek este numit după Ge-Baek, un mare general din Dinastia Baek Je (660 d.Hr.). Diagrama reprezintă disciplina sa militară severă și strictă.",
        "youtube_query": "Ge Baek ITF tul pattern",
    },
    {
        "id": "eui-am", "order": 13, "name": "Eui-Am", "korean": "의암",
        "level": "2nd Dan", "movements": 45, "diagram": "I",
        "ready_posture": "Closed Ready Stance C",
        "meaning_en": "Eui-Am is the pseudonym of Son Byong Hi, leader of the Korean independence movement on March 1, 1919. The 45 movements refer to his age when he changed the name of Dong Hak (Oriental Culture) to Chondo Kyo (Heavenly Way Religion) in 1905. The diagram represents his indomitable spirit, displayed while dedicating himself to the prosperity of his nation.",
        "meaning_ro": "Eui-Am este pseudonimul lui Son Byong Hi, lider al mișcării de independență coreene din 1 martie 1919. Cele 45 de mișcări se referă la vârsta sa când a schimbat numele Dong Hak (Cultura Orientală) în Chondo Kyo (Religia Căii Cerești) în 1905. Diagrama reprezintă spiritul său indomabil, afișat în timp ce s-a dedicat prosperității națiunii sale.",
        "youtube_query": "Eui Am ITF tul pattern",
    },
    {
        "id": "choong-jang", "order": 14, "name": "Choong-Jang", "korean": "충장",
        "level": "2nd Dan", "movements": 52,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Choong-Jang is the pseudonym given to General Kim Duk Ryang who lived during the Lee Dynasty, 14th century. This pattern ends with a left-hand attack to symbolize the tragedy of his death at 27 in prison before he was able to reach full maturity.",
        "meaning_ro": "Choong-Jang este pseudonimul dat Generalului Kim Duk Ryang, care a trăit în timpul Dinastiei Lee, secolul al XIV-lea. Acest pattern se încheie cu un atac cu mâna stângă pentru a simboliza tragedia morții sale la 27 de ani, în închisoare, înainte de a-și atinge maturitatea deplină.",
        "youtube_query": "Choong Jang ITF tul pattern",
    },
    {
        "id": "juche", "order": 15, "name": "Juche", "korean": "주체",
        "level": "2nd Dan", "movements": 45,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Juche is a philosophical idea that man is the master of everything and decides everything. In other words, the idea that man is the master of the world and his own destiny. It is said that this idea was rooted in Baekdu Mountain, which symbolizes the spirit of the Korean people. The diagram represents Baekdu Mountain.",
        "meaning_ro": "Juche este o idee filosofică conform căreia omul este stăpânul a tot și decide totul. Cu alte cuvinte, ideea că omul este stăpânul lumii și al propriului destin. Se spune că această idee a fost înrădăcinată în Muntele Baekdu, care simbolizează spiritul poporului coreean. Diagrama reprezintă Muntele Baekdu.",
        "youtube_query": "Juche ITF tul pattern",
    },
    {
        "id": "sam-il", "order": 16, "name": "Sam-Il", "korean": "삼일",
        "level": "3rd Dan", "movements": 33,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Sam-Il denotes the historical date of the independence movement of Korea which began throughout the country on March 1, 1919. The 33 movements in the pattern stand for the 33 patriots who planned the movement.",
        "meaning_ro": "Sam-Il denotă data istorică a mișcării de independență a Coreei care a început în întreaga țară pe 1 martie 1919. Cele 33 de mișcări reprezintă cei 33 de patrioți care au planificat mișcarea.",
        "youtube_query": "Sam Il ITF tul pattern",
    },
    {
        "id": "yoo-sin", "order": 17, "name": "Yoo-Sin", "korean": "유신",
        "level": "3rd Dan", "movements": 68,
        "ready_posture": "Parallel Ready Stance with Twin Side Elbow",
        "meaning_en": "Yoo-Sin is named after General Kim Yoo Sin, a commanding general during the Silla Dynasty. The 68 movements refer to the last two figures of 668 A.D., the year Korea was united. The ready posture signifies a sword drawn on the right rather than left side, symbolizing Yoo Sin's mistake of following his king's orders to fight with foreign forces against his own nation.",
        "meaning_ro": "Yoo-Sin este numit după Generalul Kim Yoo Sin, general comandant în timpul Dinastiei Silla. Cele 68 de mișcări se referă la ultimele două cifre ale anului 668 d.Hr., anul în care Coreea a fost unită. Poziția pregătit semnifică o sabie scoasă pe partea dreaptă în loc de stânga, simbolizând greșeala lui Yoo Sin de a urma ordinele regelui de a lupta cu forțe străine împotriva propriei națiuni.",
        "youtube_query": "Yoo Sin ITF tul pattern",
    },
    {
        "id": "choi-yong", "order": 18, "name": "Choi-Yong", "korean": "최영",
        "level": "3rd Dan", "movements": 46,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Choi-Yong is named after General Choi Yong, Premier and Commander-in-Chief of the Armed Forces during the 14th century Koryo Dynasty. Choi Yong was greatly respected for his loyalty, patriotism, and humility. He was executed by his subordinate commanders headed by General Yi Sung Gae, who later became the first king of the Lee Dynasty.",
        "meaning_ro": "Choi-Yong este numit după Generalul Choi Yong, Prim-ministru și Comandant Suprem al Forțelor Armate în timpul Dinastiei Koryo din secolul al XIV-lea. Choi Yong a fost foarte respectat pentru loialitatea, patriotismul și smerenia sa. A fost executat de comandanții săi subordonați conduși de Generalul Yi Sung Gae, care mai târziu a devenit primul rege al Dinastiei Lee.",
        "youtube_query": "Choi Yong ITF tul pattern",
    },
    {
        "id": "yon-gae", "order": 19, "name": "Yon-Gae", "korean": "연개",
        "level": "4th Dan", "movements": 49,
        "ready_posture": "Warrior Ready Stance A",
        "meaning_en": "Yon-Gae is named after a famous general during the Koguryo Dynasty, Yon Gae Somoon. The 49 movements refer to the last two figures of 649 A.D., the year he forced the Tang Dynasty to quit Korea after destroying nearly 300,000 of their troops at Ansi Sung.",
        "meaning_ro": "Yon-Gae este numit după un general faimos din timpul Dinastiei Koguryo, Yon Gae Somoon. Cele 49 de mișcări se referă la ultimele două cifre ale anului 649 d.Hr., anul în care a forțat Dinastia Tang să părăsească Coreea după distrugerea a aproape 300.000 dintre trupele lor la Ansi Sung.",
        "youtube_query": "Yon Gae ITF tul pattern",
    },
    {
        "id": "ul-ji", "order": 20, "name": "Ul-Ji", "korean": "을지",
        "level": "4th Dan", "movements": 42, "diagram": "ㄴL",
        "ready_posture": "Warrior Ready Stance B",
        "meaning_en": "Ul-Ji is named after general Ul-Ji Moon Dok who successfully defended Korea against a Tang's invasion force of nearly one million soldiers led by Yang Je in 612 A.D., Ul-Ji employing hit and run guerilla tactics, was able to decimate a large percentage of the force. The diagram represents his surname. The 42 movements represents the author's age when he designed the pattern.",
        "meaning_ro": "Ul-Ji este numit după generalul Ul-Ji Moon Dok, care a apărat cu succes Coreea împotriva unei forțe de invazie Tang de aproape un milion de soldați conduși de Yang Je în 612 d.Hr. Ul-Ji, folosind tactici de gherilă, a reușit să decimeze un procent mare din forță. Diagrama reprezintă numele său de familie. Cele 42 de mișcări reprezintă vârsta autorului când a creat pattern-ul.",
        "youtube_query": "Ul Ji ITF tul pattern",
    },
    {
        "id": "moon-moo", "order": 21, "name": "Moon-Moo", "korean": "문무",
        "level": "5th Dan", "movements": 61,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Moon-Moo honors the 30th king of the Silla Dynasty. His body was buried near Dae Wang Am (Great King's Rock). According to his will, the body was placed in the sea 'Where my soul shall forever defend my land against the Japanese.' It is said that the Sok Gul Am (Stone Cave) was built to guard his tomb. The Sok Gul Am is a fine example of the culture of the Silla Dynasty. The 61 movements in this pattern symbolize the last two figures of 661 A.D. when Moon Moo came to the throne.",
        "meaning_ro": "Moon-Moo onorează al 30-lea rege al Dinastiei Silla. Corpul său a fost îngropat lângă Dae Wang Am (Piatra Marelui Rege). Conform testamentului său, corpul a fost plasat în mare 'Unde sufletul meu va apăra pentru totdeauna pământul meu împotriva japonezilor.' Se spune că Sok Gul Am (Peștera de Piatră) a fost construit pentru a-i păzi mormântul. Sok Gul Am este un exemplu fin al culturii Dinastiei Silla. Cele 61 de mișcări simbolizează ultimele două cifre ale anului 661 d.Hr., când Moon Moo a urcat pe tron.",
        "youtube_query": "Moon Moo ITF tul pattern",
    },
    {
        "id": "so-san", "order": 22, "name": "So-San", "korean": "서산",
        "level": "5th Dan", "movements": 72,
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "So-San is the pseudonym of the great monk Choi Hyong Ung (1520-1604) during the Lee Dynasty. The 72 movements refer to his age when he organized a corps of monk soldiers with the assistance of his pupil Sa Myung Dang. The monk soldiers helped repulse the Japanese pirates who overran most of the Korean peninsula in 1592.",
        "meaning_ro": "So-San este pseudonimul marelui călugăr Choi Hyong Ung (1520-1604) din timpul Dinastiei Lee. Cele 72 de mișcări se referă la vârsta sa când a organizat un corp de soldați călugări cu ajutorul ucenicului său Sa Myung Dang. Soldații călugări au ajutat la respingerea piraților japonezi care au invadat cea mai mare parte a peninsulei coreene în 1592.",
        "youtube_query": "So San ITF tul pattern",
    },
    {
        "id": "se-jong", "order": 23, "name": "Se-Jong", "korean": "세종",
        "level": "6th Dan", "movements": 24, "diagram": "王",
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Se-Jong is named after the greatest Korean king, Se-Jong, who invented the Korean alphabet in 1443, and was also a noted meteorologist. The diagram represents the king, while the 24 movements refer to the 24 letters of the Korean alphabet.",
        "meaning_ro": "Se-Jong este numit după cel mai mare rege coreean, Se-Jong, care a inventat alfabetul coreean în 1443 și a fost, de asemenea, un meteorolog renumit. Diagrama reprezintă regele, iar cele 24 de mișcări se referă la cele 24 de litere ale alfabetului coreean.",
        "youtube_query": "Se Jong ITF tul pattern",
    },
    {
        "id": "tong-il", "order": 24, "name": "Tong-Il", "korean": "통일",
        "level": "7th Dan", "movements": 56, "diagram": "I",
        "ready_posture": "Parallel Ready Stance",
        "meaning_en": "Tong-Il denotes the resolution of the unification of Korea which has been divided since 1945. The diagram symbolizes the homogeneous race.",
        "meaning_ro": "Tong-Il denotă rezoluția unificării Coreei, care a fost divizată din 1945. Diagrama simbolizează rasa omogenă.",
        "youtube_query": "Tong Il ITF tul pattern",
    },
]


# ============================================================
# ENCYCLOPEDIA — verbatim from the General Choi encyclopedia
# ============================================================
ENCYCLOPEDIA = [
    {
        "id": "definition",
        "category": "philosophy",
        "title_en": "Definition of Taekwon-Do",
        "title_ro": "Definiția Taekwon-Do",
        "content_en": "TAEKWON-DO… A way of life.\n\nTo put it simply, Taekwon-Do is a version of unarmed combat designed for the purpose of self-defence. It is more than just that, however. It is the scientific use of the body in the method of self-defence; a body that has gained the ultimate use of its facilities through intensive physical and mental training.\n\nIt is a martial art that has no equal in either power or technique. Though it is a martial art, its discipline, technique and mental training are the mortar for building a strong sense of justice, fortitude, humility and resolve. It is this mental conditioning that separates the true practitioner from the sensationalist, content with mastering only the fighting aspects of the art.\n\nTranslated literally, 'Tae' stands for jumping or flying, to kick or smash with the foot. 'Kwon' denotes the fist — chiefly to punch or destroy with the hand or fist. 'Do' means an art or way — the right way built and paved by the saints and sages in the past. Thus taken collectively, 'Taekwon-Do' indicates the mental training and the techniques of unarmed combat for self-defence as well as health, involving the skilled application of punches, kicks, blocks and dodges with bare hands and feet to the rapid destruction of the moving opponent or opponents.\n\n— Gen. Choi Hong Hi",
        "content_ro": "TAEKWON-DO… Un mod de viață.\n\nMai simplu spus, Taekwon-Do este o formă de luptă fără arme, concepută în scopul autoapărării. Este însă mai mult decât atât. Este utilizarea științifică a corpului în metoda autoapărării; un corp care a obținut utilizarea supremă a facultăților sale printr-un antrenament fizic și mental intens.\n\nEste o artă marțială fără egal în putere sau tehnică. Deși este o artă marțială, disciplina, tehnica și antrenamentul mental sunt mortarul pentru construirea unui puternic simț al dreptății, tăriei sufletești, smereniei și hotărârii. Acest condiționament mental îl separă pe adevăratul practicant de senzaționalist, mulțumit doar cu aspectele de luptă ale artei.\n\nTradus literal, 'Tae' înseamnă a sări sau a zbura, a lovi cu piciorul sau a sparge cu piciorul. 'Kwon' înseamnă pumnul — în principal a lovi sau a distruge cu mâna sau pumnul. 'Do' înseamnă o artă sau cale — calea cea dreaptă construită și pavată de sfinții și înțelepții din trecut. Luat în totalitate, 'Taekwon-Do' indică antrenamentul mental și tehnicile de luptă fără arme pentru autoapărare și sănătate.\n\n— Gen. Choi Hong Hi",
    },
    {
        "id": "general-choi-hong-hi",
        "category": "history",
        "title_en": "General Choi Hong Hi — The Founder",
        "title_ro": "Generalul Choi Hong Hi — Fondatorul",
        "content_en": "General Choi Hong Hi (9 November 1918 – 15 June 2002) was the founder of Taekwon-Do, often referred to as 'the Father of Taekwon-Do'. He was born in the Hwa Dae, Myongchon district of what is now North Korea. As a frail boy, he studied calligraphy under one of Korea's most renowned teachers, Mr. Han Il Dong, who also taught him the ancient Korean martial art of Taek Kyon to strengthen his health.\n\nIn 1937 he travelled to Japan for further education. While in Kyoto he met a fellow Korean, Mr. Kim, who was teaching the Japanese martial art of Karate. Within a couple of years Choi obtained his black belt, becoming one of the first Korean Karate instructors in Japan.\n\nDuring his military career he combined elements of Taek Kyon and Karate to develop a martial art unique to Korea. On April 11, 1955, this new art was officially named 'Taekwon-Do'. He founded the International Taekwon-Do Federation (ITF) on March 22, 1966.\n\nGeneral Choi authored the 15-volume Encyclopedia of Taekwon-Do, the definitive reference for the art. He spent his life traveling to over one hundred countries to teach and promote his creation. His motto: 'I shall be a champion of freedom and justice.'",
        "content_ro": "Generalul Choi Hong Hi (9 noiembrie 1918 – 15 iunie 2002) a fost fondatorul Taekwon-Do, deseori numit 'Tatăl Taekwon-Do'. S-a născut în districtul Hwa Dae, Myongchon, în ceea ce este acum Coreea de Nord. Fiind un băiat fragil, a studiat caligrafia sub îndrumarea unuia dintre cei mai renumiți profesori coreeni, domnul Han Il Dong, care l-a învățat și arta marțială coreeană Taek Kyon pentru a-i întări sănătatea.\n\nÎn 1937 a plecat în Japonia pentru continuarea studiilor. La Kyoto l-a întâlnit pe domnul Kim, care preda Karate. În câțiva ani, Choi a obținut centura neagră, devenind unul dintre primii instructori coreeni de Karate din Japonia.\n\nÎn timpul carierei militare a combinat elemente din Taek Kyon și Karate pentru a crea o artă marțială unică pentru Coreea. Pe 11 aprilie 1955, această nouă artă a fost numită oficial 'Taekwon-Do'. A fondat Federația Internațională de Taekwon-Do (ITF) pe 22 martie 1966.\n\nGeneralul Choi a scris Enciclopedia Taekwon-Do în 15 volume, referința definitivă a artei. Și-a petrecut viața călătorind în peste o sută de țări pentru a preda și promova creația sa. Motto-ul său: 'Voi fi un campion al libertății și al dreptății.'",
    },
    {
        "id": "tenets",
        "category": "philosophy",
        "title_en": "The Five Tenets (Taekwon-Do Jungshin)",
        "title_ro": "Cele Cinci Principii (Taekwon-Do Jungshin)",
        "content_en": "Taekwon-Do aims to achieve:\n\n• Courtesy (Ye Ui)\n• Integrity (Yom Chi)\n• Perseverance (In Nae)\n• Self-Control (Guk Gi)\n• Indomitable Spirit (Baekjul Boolgool)\n\nCOURTESY (Ye Ui) — Courtesy is an unwritten regulation prescribed by ancient teachers of philosophy. Taekwon-Do students should: promote mutual concessions; be ashamed of their vices; be polite; encourage justice and humanity; distinguish instructor from student, senior from junior, elder from younger; behave according to etiquette; respect others' possessions; handle matters with fairness and sincerity; refrain from giving or accepting any gift when in doubt.\n\nINTEGRITY (Yom Chi) — One must be able to define right and wrong and have the conscience, if wrong, to feel guilt. Examples where integrity is lacking include: an instructor who misrepresents his art; a student who 'fixes' breaking materials; an instructor who teaches for materialistic gains; a student who requests or buys rank; a student whose actions do not live up to his words.\n\nPERSEVERANCE (In Nae) — 'Patience leads to virtue or merit.' To achieve something — whether a higher degree or the perfection of a technique — one must set his goal then constantly persevere. Confucius said: 'One who is impatient in trivial matters can seldom achieve success in matters of great importance.'\n\nSELF-CONTROL (Guk Gi) — Extremely important inside and outside the dojang, in free sparring or personal affairs. Lao-Tzu: 'The term of stronger is the person who wins over oneself rather than someone else.'\n\nINDOMITABLE SPIRIT (Baekjul Boolgool) — A serious student of Taekwon-Do will at all times be modest and honest. If confronted with injustice, he will deal with the belligerent without any fear or hesitation, with indomitable spirit, regardless of whosoever and however many they may be. Confucius declared: 'It is an act of cowardice to fail to speak out against injustice.'",
        "content_ro": "Taekwon-Do aspiră să atingă:\n\n• Curtoazie (Ye Ui)\n• Integritate (Yom Chi)\n• Perseverență (In Nae)\n• Autocontrol (Guk Gi)\n• Spirit Indomabil (Baekjul Boolgool)\n\nCURTOAZIE (Ye Ui) — Curtoazia este o regulă nescrisă prescrisă de profesori antici de filosofie. Studenții Taekwon-Do ar trebui: să promoveze concesiile reciproce; să se rușineze de viciile proprii; să fie politicoși; să încurajeze dreptatea și umanitatea; să distingă instructorul de student, seniorul de junior, vârstnicul de tânăr; să se comporte conform etichetei; să respecte bunurile altora; să trateze chestiunile cu echitate și sinceritate.\n\nINTEGRITATE (Yom Chi) — Trebuie să fii capabil să definești binele și răul și să ai conștiința, dacă greșești, să simți vinovăție. Exemple unde integritatea lipsește: instructorul care își reprezintă greșit arta; studentul care 'aranjează' materialele de spargere; instructorul care predă pentru câștiguri materiale; studentul care cere sau cumpără un grad; studentul ale cărui acțiuni nu sunt la înălțimea cuvintelor sale.\n\nPERSEVERENȚĂ (In Nae) — 'Răbdarea duce la virtute sau merit.' Pentru a realiza ceva — fie un grad mai înalt, fie perfecționarea unei tehnici — trebuie să-ți stabilești obiectivul apoi să perseverezi constant. Confucius a spus: 'Cel care este nerăbdător în chestiuni banale poate rareori să reușească în chestiuni de mare importanță.'\n\nAUTOCONTROL (Guk Gi) — Extrem de important în și în afara dojang-ului, în sparring liber sau în treburi personale. Lao-Tzu: 'Termenul mai puternic este persoana care învinge asupra sa, mai degrabă decât asupra altcuiva.'\n\nSPIRIT INDOMABIL (Baekjul Boolgool) — Un student serios de Taekwon-Do va fi întotdeauna modest și onest. Dacă se confruntă cu nedreptatea, se va confrunta cu beligerantul fără frică sau ezitare, cu spirit indomabil, indiferent cine și câți ar fi.",
    },
    {
        "id": "student-oath",
        "category": "philosophy",
        "title_en": "Student Oath",
        "title_ro": "Jurământul Studentului",
        "content_en": "I shall observe the tenets of Taekwon-Do.\nI shall respect the instructor and seniors.\nI shall never misuse Taekwon-Do.\nI shall be a champion of freedom and justice.\nI shall build a more peaceful world.",
        "content_ro": "Voi respecta principiile Taekwon-Do.\nVoi respecta instructorul și seniorii.\nNu voi folosi niciodată în mod abuziv Taekwon-Do.\nVoi fi un campion al libertății și al dreptății.\nVoi construi o lume mai pașnică.",
    },
    {
        "id": "theory-of-power",
        "category": "theory",
        "title_en": "Theory of Power (Him Ui Wolli)",
        "title_ro": "Teoria Puterii (Him Ui Wolli)",
        "content_en": "The beginning student may ask: 'Where does one obtain the power to create the devastating results attributed to Taekwon-Do?' This power is attributed to the utilization of a person's full potential through the mathematical application of Taekwon-Do techniques. The average person uses only 10 to 20 percent of his potential. Anyone, regardless of size, age, or sex who can condition himself to use 100 percent of his potential can also perform the same destructive techniques. The factors are:\n\n1. REACTION FORCE (Bandong Ryok) — According to Newton's Law, every force has an equal and opposite force. If your opponent is rushing toward you at high speed, the force of your blow plus his onslaught is impressive. A punch with the right fist is also aided by pulling back the left fist to the hip with equal force.\n\n2. CONCENTRATION (Jip Joong) — By applying the impact force onto the smallest target area, you concentrate the force and increase its effect. The shorter the time of concentration, the greater the power. Mobilize every muscle of the body — particularly the bigger hip and abdominal muscles — toward the appropriate tool at the proper time, and concentrate them onto the opponent's vital spot. This is why the hip and abdomen are jerked slightly before the hands and feet in any action.\n\n3. EQUILIBRIUM (Kyun Hyung) — Balance is of utmost importance. The stance should always be stable yet flexible, for both offensive and defensive movements. Equilibrium is classified into dynamic and static stability. The center of gravity must fall on a straight line midway between both legs (or in the center of the foot if weight is concentrated on one foot). The heel of the rear foot must never be off the ground at the point of impact.\n\n4. BREATH CONTROL (Hohup Jojul) — Controlled breathing affects stamina and speed and conditions the body to receive a blow. A sharp exhale at the moment of impact, with stopped breath during the execution of a movement, tenses the abdomen and concentrates maximum effort. Slow inhaling helps preparation. Important rule: NEVER inhale while focusing a block or blow.\n\n5. MASS (Zilyang) — Maximum kinetic energy is obtained from maximum body weight and speed. Body weight is increased by turning the hip in the same direction as the attacking or blocking tool, and by utilizing a springing knee action — slightly raising the hip at the start of the motion and lowering it at the moment of impact (the sine wave).\n\n6. SPEED (Sokdo) — Speed is the most essential factor of force. Force = mass × acceleration (F = ma) or P = ½ × M × V². If mass is tripled, power triples; if speed is tripled, power increases NINE-FOLD. According to kinetic energy, every object increases its weight in a downward movement; thus, at the moment of impact, the hand becomes lower than the shoulder and the foot lower than the hip.",
        "content_ro": "Studentul începător poate întreba: 'De unde se obține puterea care creează rezultatele devastatoare atribuite Taekwon-Do?' Această putere este atribuită utilizării potențialului complet al unei persoane prin aplicarea matematică a tehnicilor Taekwon-Do. Persoana obișnuită folosește doar 10-20% din potențialul său. Oricine, indiferent de mărime, vârstă sau sex, care se poate condiționa să folosească 100% din potențial, poate executa aceleași tehnici devastatoare. Factorii sunt:\n\n1. FORȚA DE REACȚIE (Bandong Ryok) — Conform legii lui Newton, fiecare forță are o forță egală și opusă. Dacă adversarul se năpustește spre tine cu viteză mare, forța loviturii tale plus asaltul lui este impresionantă. Un pumn cu pumnul drept este ajutat și prin tragerea pumnului stâng spre șold cu forță egală.\n\n2. CONCENTRARE (Jip Joong) — Aplicând forța de impact pe cea mai mică zonă țintă, concentrezi forța și îi crești efectul. Cu cât timpul de concentrare este mai scurt, cu atât puterea este mai mare. Mobilizează fiecare mușchi al corpului — în special mușchii mari ai șoldului și abdomenului — către instrumentul potrivit la momentul potrivit, și concentrează-i pe punctul vital al adversarului.\n\n3. ECHILIBRU (Kyun Hyung) — Echilibrul este de o importanță maximă. Poziția trebuie să fie întotdeauna stabilă, dar flexibilă, atât pentru mișcările ofensive, cât și defensive. Echilibrul se clasifică în stabilitate dinamică și statică. Centrul de greutate trebuie să cadă pe o linie dreaptă la jumătatea distanței dintre cele două picioare. Călcâiul piciorului din spate nu trebuie să fie niciodată ridicat de pe sol în momentul impactului.\n\n4. CONTROLUL RESPIRAȚIEI (Hohup Jojul) — Respirația controlată afectează rezistența și viteza, condiționează corpul să primească o lovitură. O expirație ascuțită în momentul impactului, cu respirația oprită în timpul execuției unei mișcări, tensionează abdomenul și concentrează efortul maxim. Regulă importantă: NU INSPIRA NICIODATĂ în timp ce focalizezi un blocaj sau o lovitură.\n\n5. MASA (Zilyang) — Energia cinetică maximă se obține din greutatea corporală maximă și viteză. Greutatea corporală crește prin rotirea șoldului în aceeași direcție cu instrumentul de atac sau blocaj, și prin utilizarea unei acțiuni de resort a genunchiului — ridicarea ușoară a șoldului la începutul mișcării și coborârea lui în momentul impactului (sine wave).\n\n6. VITEZA (Sokdo) — Viteza este cel mai esențial factor al forței. Forța = masa × accelerația (F = ma) sau P = ½ × M × V². Dacă masa este triplată, puterea se triplează; dacă viteza este triplată, puterea crește DE NOUĂ ORI.",
    },
    {
        "id": "composition",
        "category": "theory",
        "title_en": "Composition of Taekwon-Do (Goosung) — Why 24 Patterns",
        "title_ro": "Compoziția Taekwon-Do (Goosung) — De ce 24 de Pattern-uri",
        "content_en": "Taekwon-Do is composed of fundamental movements, patterns, dallyon, sparring and self-defence techniques that are so closely related that it is impossible to segregate one phase of instruction from another. Like the Deity, the cycle of Taekwon-Do has no beginning or end. As in military training:\n\n1. Fundamental Movements = Individual soldier's basic training\n2. Dallyon = Maintenance of equipment\n3. Patterns = Platoon tactics\n4. Sparring = Field exercises in simulated combat\n5. Self-defence = Actual combat\n\nThe Reason for 24 Patterns:\n\n'The life of a human being, perhaps 100 years, can be considered as a day when compared with eternity. Therefore, we mortals are no more than simple travellers who pass by the eternal years of an aeon in a day. It is evident that no one can live more than a limited amount of time. Nevertheless, most people foolishly enslave themselves to materialism as if they could live for thousands of years. And some people strive to bequeath a good spiritual legacy for coming generations, in this way gaining immortality. Obviously, the spirit is perpetual while material is not. Therefore, what we can do to leave behind something for the welfare of mankind is, perhaps, the most important thing in our lives. Here I leave Taekwon-Do for mankind as a trace of man of the late 20th century. The 24 patterns represent 24 hours, one day, or all my life.'\n\n— General Choi Hong Hi",
        "content_ro": "Taekwon-Do este compus din mișcări fundamentale, pattern-uri, dallyon, sparring și tehnici de autoapărare care sunt atât de strâns legate, încât este imposibil să separi o fază de instruire de alta. Ca și Divinitatea, ciclul Taekwon-Do nu are nici început, nici sfârșit. Ca în antrenamentul militar:\n\n1. Mișcări Fundamentale = Antrenamentul de bază al soldatului\n2. Dallyon = Întreținerea echipamentului\n3. Pattern-uri = Tactici de pluton\n4. Sparring = Exerciții de teren în luptă simulată\n5. Autoapărare = Luptă reală\n\nMotivul pentru 24 de Pattern-uri:\n\n'Viața unei ființe umane, poate 100 de ani, poate fi considerată o zi în comparație cu eternitatea. Prin urmare, noi muritorii nu suntem decât simpli călători care trec pe lângă anii eterni ai unei ere într-o zi. Cei 24 de pattern-uri reprezintă 24 de ore, o zi, sau toată viața mea.'\n\n— Generalul Choi Hong Hi",
    },
    {
        "id": "belt-colors",
        "category": "philosophy",
        "title_en": "Meaning of Belt Colors",
        "title_ro": "Semnificația Culorilor Centurilor",
        "content_en": "The colors have not been arbitrarily chosen. They are steeped in tradition: black, red and blue denoted the various levels of hierarchy during the Koguryo and Silla Dynasties.\n\nWHITE — Signifies innocence, as that of a beginning student who has no previous knowledge of Taekwon-Do.\n\nYELLOW — Signifies the Earth from which a plant sprouts and takes root as the Taekwon-Do foundation is being laid.\n\nGREEN — Signifies the plant's growth as the Taekwon-Do skill begins to develop.\n\nBLUE — Signifies the Heaven, towards which the plant matures into a towering tree as training in Taekwon-Do progresses.\n\nRED — Signifies danger, cautioning the student to exercise control and warning the opponent to stay away.\n\nBLACK — Opposite of white, therefore signifying the maturity and proficiency in Taekwon-Do. It also indicates the wearer's imperviousness to darkness and fear.\n\nThe belt is wrapped around the waist only ONCE (decided July 1st, 1985). The 'one' symbolizes:\n• Ohdoilkwan (pursue one goal whatsoever, once it is determined)\n• Ilpyondanshim (serve one master with unshakable loyalty)\n• Ilkyokpilsung (gain a victory in one blow)",
        "content_ro": "Culorile nu au fost alese arbitrar. Ele sunt impregnate de tradiție: negrul, roșul și albastrul desemnau diversele niveluri de ierarhie în timpul Dinastiilor Koguryo și Silla.\n\nALB — Semnifică inocența, ca cea a unui student începător care nu are cunoștințe anterioare despre Taekwon-Do.\n\nGALBEN — Semnifică Pământul din care răsare și prinde rădăcină o plantă, în timp ce se așază fundația Taekwon-Do.\n\nVERDE — Semnifică creșterea plantei pe măsură ce abilitatea Taekwon-Do începe să se dezvolte.\n\nALBASTRU — Semnifică Cerul, spre care planta se maturizează într-un copac înalt, pe măsură ce antrenamentul progresează.\n\nROȘU — Semnifică pericolul, avertizând studentul să exercite control și avertizându-l pe adversar să stea departe.\n\nNEGRU — Opus albului, deci semnifică maturitatea și competența. Indică, de asemenea, imunitatea purtătorului față de întuneric și frică.\n\nCentura se înfășoară în jurul taliei o SINGURĂ DATĂ (decis la 1 iulie 1985). 'Unul' simbolizează:\n• Ohdoilkwan (urmărește un singur scop odată determinat)\n• Ilpyondanshim (slujește un singur maestru cu loialitate de neclintit)\n• Ilkyokpilsung (obține victoria într-o singură lovitură)",
    },
    {
        "id": "title-function",
        "category": "philosophy",
        "title_en": "Titles & Functions (Chingho wa Kinung)",
        "title_ro": "Titluri & Funcții (Chingho wa Kinung)",
        "content_en": "In Taekwon-Do each title is determined according to the rank as follows:\n\n• 1st – 3rd Degree → Assistant Instructor (when necessary) — BOOSABUM (부사범)\n• 4th – 6th Degree → Instructor — SABUM (사범)\n• 7th – 8th Degree → Master — SAHYUN (사현)\n• 9th Degree → Grand Master — SASEONG (사성)\n\nA unique and ideal spirit of chivalry — characteristic of martial-art practitioners — is achieved by designating an appropriate title to each black-belt holder. This makes a clear distinction between seniors and juniors, motivating the former to act with discretion and setting an exemplary standard, while the latter strive for self-improvement to emulate their mentors.",
        "content_ro": "În Taekwon-Do fiecare titlu este determinat în funcție de grad astfel:\n\n• 1 – 3 Dan → Instructor Asistent (când este necesar) — BOOSABUM (부사범)\n• 4 – 6 Dan → Instructor — SABUM (사범)\n• 7 – 8 Dan → Maestru — SAHYUN (사현)\n• 9 Dan → Mare Maestru — SASEONG (사성)\n\nUn spirit unic și ideal de cavalerism este obținut prin desemnarea unui titlu adecvat fiecărui purtător de centură neagră. Aceasta face o distincție clară între seniori și juniori, motivându-i pe primii să acționeze cu discreție și stabilind un standard exemplar, în timp ce ultimii se străduiesc pentru auto-îmbunătățire pentru a-și emula mentorii.",
    },
    {
        "id": "system-of-rank",
        "category": "philosophy",
        "title_en": "System of Rank (Dan Gup Jedo)",
        "title_ro": "Sistemul de Grade (Dan Gup Jedo)",
        "content_en": "In Taekwon-Do, character development, fortitude, tenacity, and technique are graded as well as individual capacity. The promotional scale is divided into nineteen ranks — 10 grades (Gups) and 9 degrees (Dans). Gups begin at 10th grade (lowest) and end at 1st grade. Dans begin at 1st degree and end at the ultimate 9th degree.\n\nThere is significance in the numbering. The number 9 is the highest single-digit number AND is 3 × 3. Three is the most esteemed of all numbers in the Orient. The Chinese character for three (三) symbolizes: heaven (top), mortals (middle), and earth (bottom). Multiplying 3 × 3 = 9 makes 9 the highest of the high — therefore the 9th degree is the highest rank.\n\nWhen 9 is multiplied by any single digit and the result's digits are summed, the answer is always 9 (e.g. 9 × 7 = 63, 6 + 3 = 9). Since 9 is the only digit with this property, it is the most positive figure.\n\nThe Dans are further divided into three classes:\n• 1st – 3rd Dan → Novice stages of black belt\n• 4th – 6th Dan → Expert class\n• 7th – 9th Dan → Masters",
        "content_ro": "În Taekwon-Do, dezvoltarea caracterului, tăria, tenacitatea și tehnica sunt notate la fel ca și capacitatea individuală. Scara de promovare este împărțită în 19 grade — 10 Kup și 9 Dan. Kup-urile încep cu 10 (cel mai jos) și se încheie cu 1. Dan-urile încep cu 1 și se încheie cu 9.\n\nNumărul 9 este cel mai mare număr cu o singură cifră ȘI este 3 × 3. Trei este cel mai prețuit dintre toate numerele în Orient. Caracterul chinezesc pentru trei (三) simbolizează: cerul (sus), muritorii (mijloc) și pământul (jos). Înmulțind 3 × 3 = 9 face din 9 cel mai înalt — prin urmare gradul 9 este cel mai înalt.\n\nDan-urile sunt împărțite în trei clase:\n• 1 – 3 Dan → Etape de începător ale centurii negre\n• 4 – 6 Dan → Clasa experților\n• 7 – 9 Dan → Maeștri",
    },
    {
        "id": "history-of-tkd",
        "category": "history",
        "title_en": "History & Korean Roots",
        "title_ro": "Istorie & Rădăcini Coreene",
        "content_en": "Taekwon-Do's roots reach over 2,000 years into Korean martial history. The ancient kingdoms developed Taek Kyon (Koguryo), Subak, and the Hwarang warrior code of the Silla Dynasty (loyalty, filial piety, faithfulness, courage, justice). General Choi Hong Hi created and introduced the new art in 1946 in what is now South Korea, combining the most effective elements of Taek Kyon and Karate while removing what was inefficient and adding scientific principles based on Newtonian physics — the famous Theory of Power.\n\nApril 11, 1955: the name 'Taekwon-Do' is officially adopted.\nMarch 22, 1966: the International Taekwon-Do Federation (ITF) is founded with nine member nations.\n\nGeneral Choi: 'The true Taekwon-Do knows no boundaries of countries; it is a universal art of self-defence.'",
        "content_ro": "Rădăcinile Taekwon-Do se întind cu peste 2.000 de ani în istoria marțială coreeană. Vechile regate au dezvoltat Taek Kyon (Koguryo), Subak și codul războinic Hwarang al Dinastiei Silla (loialitate, pietate filială, credință, curaj, dreptate). Generalul Choi Hong Hi a creat și a introdus noua artă în 1946 în ceea ce este acum Coreea de Sud, combinând cele mai eficiente elemente din Taek Kyon și Karate, eliminând ce era ineficient și adăugând principii științifice bazate pe fizica newtoniană — celebra Teorie a Puterii.\n\n11 aprilie 1955: numele 'Taekwon-Do' este adoptat oficial.\n22 martie 1966: este fondată Federația Internațională de Taekwon-Do (ITF) cu nouă națiuni membre.",
    },
    {
        "id": "charter",
        "category": "philosophy",
        "title_en": "Charter of Taekwon-Do (Hun Jang)",
        "title_ro": "Carta Taekwon-Do (Hun Jang)",
        "content_en": "PREAMBLE — Since Taekwon-Do is an art of self-defence which aims at noble moral rearmament, a high degree of intellectual achievement, graceful techniques, and beauty of physical form, it can be considered as a part of one's daily life, just as are breathing and thinking.\n\nPART 1 — Through scientific practice of Taekwon-Do one can significantly improve health and nourish the intellect. One can be in a position to aid others in the cause of justice, thereby promoting social ethics and morals.\n\nPART 2 — One ought to continue studying the art of Taekwon-Do to learn techniques of power and grace, and to enlarge his spiritual realm.\n\nPART 3 — Human beings need not become avaricious but ought to remain always humble and merciful.\n\nPART 4 — All students are subject to the same rules of conduct regardless of station, origin, or religion — they demonstrate the essential equality and brotherhood of man.\n\nPART 5 — Modern society's preoccupation with material excess can be balanced by self-discipline, sacrifice, mutual help and devotion.\n\nPART 6 — Those who devote themselves to their fellows are always helpful toward juniors and respectful toward instructors and seniors.\n\nCONCLUSION — A beginning constitutes a significant part of the whole endeavor. Therefore, students of Taekwon-Do should not fail to take action whenever to do so might benefit the society.",
        "content_ro": "PREAMBUL — Deoarece Taekwon-Do este o artă a autoapărării care urmărește rearmare morală nobilă, un grad înalt de realizare intelectuală, tehnici grațioase și frumusețea formei fizice, poate fi considerat parte din viața de zi cu zi, la fel cum sunt respirația și gândirea.\n\nPARTEA 1 — Prin practica științifică a Taekwon-Do se poate îmbunătăți semnificativ sănătatea și hrăni intelectul.\n\nPARTEA 2 — Se cuvine să continuăm studierea artei pentru a învăța tehnici de putere și grație și pentru a ne extinde tărâmul spiritual.\n\nPARTEA 3 — Ființele umane nu trebuie să devină avare, ci să rămână întotdeauna smerite și milostive.\n\nPARTEA 4 — Toți studenții sunt supuși acelorași reguli de conduită indiferent de poziție, origine sau religie — ei demonstrează egalitatea esențială și fraternitatea omului.\n\nPARTEA 5 — Preocuparea societății moderne cu excesul material poate fi echilibrată prin auto-disciplină, sacrificiu, ajutor reciproc și devotament.\n\nPARTEA 6 — Cei care se devotează semenilor sunt întotdeauna utili juniorilor și respectuoși față de instructori și seniori.\n\nCONCLUZIE — Un început constituie o parte semnificativă a întregului efort. Studenții Taekwon-Do nu trebuie să eșueze în a lua măsuri ori de câte ori acest lucru poate aduce beneficii societății.",
    },
    {
        "id": "song",
        "category": "history",
        "title_en": "Song of Taekwon-Do (Taekwon-Do Norae)",
        "title_ro": "Cântecul Taekwon-Do (Taekwon-Do Norae)",
        "content_en": "Words by Choi Hong Hi · Music by Kim Yoon Yung\n\n1. We are learning Taekwon-Do with the purpose of building a better and more peaceful world. So let us develop a noble character with fantastic technique to keep fighting for the weaker as a missionary of humanity and justice.\n\n2. Taekwon-Do has blossomed again after long hibernation and it has been fast spreading everywhere regardless of religion, race and ism — under the ideal of courtesy, integrity, perseverance, self-control and indomitable spirit.",
        "content_ro": "Versuri de Choi Hong Hi · Muzică de Kim Yoon Yung\n\n1. Învățăm Taekwon-Do cu scopul de a construi o lume mai bună și mai pașnică. Așadar, să dezvoltăm un caracter nobil cu o tehnică fantastică pentru a continua să luptăm pentru cei slabi ca misionari ai umanității și dreptății.\n\n2. Taekwon-Do a înflorit din nou după o lungă hibernare și se răspândește rapid pretutindeni indiferent de religie, rasă și -ism — sub idealul curtoaziei, integrității, perseverenței, autocontrolului și spiritului indomabil.",
    },
    {
        "id": "dojang-etiquette",
        "category": "philosophy",
        "title_en": "Dojang Etiquette",
        "title_ro": "Eticheta în Dojang",
        "content_en": "The dojang (도장) — the training hall — is a place of respect and discipline.\n\n• Bow when entering and leaving the dojang\n• Bow to the flag and the instructor at the start and end of class\n• Address instructors as Boosabum (1-3 Dan), Sabum (4-6), Sahyun (7-8), or Saseong (9)\n• Keep the dobok (uniform) clean and properly tied\n• Remove footwear before entering the training area\n• No unnecessary talking during class\n• Arrive on time; if late, wait at the edge until invited in\n• Senior students help junior students with respect — and juniors are humble in return",
        "content_ro": "Dojang-ul (도장) — sala de antrenament — este un loc al respectului și disciplinei.\n\n• Înclină-te la intrarea și ieșirea din dojang\n• Înclină-te în fața drapelului și instructorului la începutul și sfârșitul clasei\n• Adresează-te instructorilor cu Boosabum (1-3 Dan), Sabum (4-6), Sahyun (7-8) sau Saseong (9)\n• Păstrează dobok-ul curat și corect legat\n• Scoate încălțămintea înainte de a intra în zona de antrenament\n• Fără vorbe inutile în timpul clasei\n• Sosește la timp; dacă întârzii, așteaptă la margine până ești invitat\n• Studenții seniori îi ajută pe juniori cu respect — iar juniorii sunt smeriți la rândul lor",
    },
    {
        "id": "sine-wave",
        "category": "theory",
        "title_en": "Sine Wave Motion",
        "title_ro": "Mișcarea Sine Wave",
        "content_en": "The Sine Wave is the vertical body movement that distinguishes ITF Taekwon-Do. The body follows three phases:\n\n1. DOWN — slightly lower the hip\n2. UP — rise smoothly while preparing the technique\n3. DOWN — drop the body weight into the technique at the moment of impact\n\nThis vertical motion adds gravitational mass to every technique, increasing power according to F = ma. The hip is raised at the beginning of the motion and lowered at the moment of impact (Mass principle, see Theory of Power). Without the sine wave, the foot moves in a horizontal wave instead — the result is less power. Without proper hip rotation, the foot moves in a saw-tooth wave — again, less power.",
        "content_ro": "Sine Wave este mișcarea verticală a corpului care distinge ITF Taekwon-Do. Corpul urmează trei faze:\n\n1. JOS — coboară ușor șoldul\n2. SUS — ridică-te lin în timp ce pregătești tehnica\n3. JOS — coboară greutatea corporală în tehnică în momentul impactului\n\nAceastă mișcare verticală adaugă masă gravitațională fiecărei tehnici, mărind puterea conform F = ma. Șoldul este ridicat la începutul mișcării și coborât în momentul impactului (principiul Masei). Fără sine wave, piciorul se mișcă într-o undă orizontală — rezultatul este mai puțină putere.",
    },
    {
        "id": "training-secrets",
        "category": "theory",
        "title_en": "Training Secrets of Taekwon-Do",
        "title_ro": "Secretele Antrenamentului în Taekwon-Do",
        "content_en": "General Choi highlighted several secrets to effective training:\n1. To study the theory of power thoroughly.\n2. To understand the purpose and method of each movement clearly.\n3. To bring the movement of eyes, hands, feet and breath into a single coordinated action.\n4. To choose the appropriate attacking tool for each vital spot.\n5. To become familiar with the correct angle and distance for attack and defence.\n6. Keep both the arms and legs bent slightly while the movement is in motion.\n7. All movements must begin with a backward motion with very few exceptions. However, once the movement is in motion it should not be stopped before reaching the target.\n8. To create a sine wave during the movement by utilizing the knee spring properly.",
        "content_ro": "Generalul Choi a evidențiat 8 secrete pentru un antrenament eficient:\n1. Să studiezi temeinic teoria puterii.\n2. Să înțelegi clar scopul și metoda fiecărei mișcări.\n3. Să aduci mișcarea ochilor, mâinilor, picioarelor și respirația într-o singură acțiune coordonată.\n4. Să alegi arma de atac potrivită pentru fiecare punct vital.\n5. Să te familiarizezi cu unghiul și distanța corectă pentru atac și apărare.\n6. Să ții atât brațele, cât și picioarele ușor îndoite în timpul mișcării.\n7. Toate mișcările trebuie să înceapă cu o mișcare înapoi, cu foarte puține excepții. Odată inițiată, mișcarea nu trebuie oprită înainte de a atinge ținta.\n8. Să creezi un 'sine wave' (undă sinusoidală) în timpul mișcării, utilizând corect flexia genunchilor."
    },
    {
        "id": "vital-spots",
        "category": "theory",
        "title_en": "Vital Spots (Kupso)",
        "title_ro": "Punctele Vitale (Kupso)",
        "content_en": "A vital spot in Taekwon-Do is defined as any sensitive or vulnerable area on the body that is susceptible to an attack.\nThe body is divided into 3 main sections for targeting:\n1. High Section (Nopunde): Above the neck/shoulders (eyes, temples, philtrum, jaw).\n2. Middle Section (Kaunde): Between the shoulders and the umbilicus (solar plexus, floating ribs, sternum).\n3. Low Section (Najunde): Below the umbilicus (groin, knees, shins, instep).\nStriking the correct vital spot with the appropriate tool is essential for effective self-defence.",
        "content_ro": "Un punct vital în Taekwon-Do este definit ca orice zonă sensibilă sau vulnerabilă a corpului, susceptibilă la un atac.\nCorpul este împărțit în 3 secțiuni principale pentru țintire:\n1. Secțiunea Înaltă (Nopunde): Deasupra gâtului/umerilor (ochi, tâmple, filtrum, maxilar).\n2. Secțiunea Mijlocie (Kaunde): Între umeri și ombilic (plexul solar, coastele flotante, stern).\n3. Secțiunea Joasă (Najunde): Sub ombilic (vintre, genunchi, tibii, instep).\nLoviturile pe punctul vital corect cu arma adecvată sunt esențiale pentru o autoapărare eficientă."
    },
    {
        "id": "system-of-sparring",
        "category": "theory",
        "title_en": "System of Sparring (Matsogi)",
        "title_ro": "Sistemul de Sparring (Matsogi)",
        "content_en": "Sparring is the physical application of the Taekwon-Do techniques against an actual moving opponent or opponents.\nIt is divided into:\n1. Pre-arranged Sparring (Yaksok Matsogi): Movements are planned in advance (3-step, 2-step, 1-step).\n2. Free Sparring (Jayu Matsogi): Unscripted combat with controlled attacks.\n3. Model Sparring (Mobum Matsogi): Displaying techniques with a partner for demonstration purposes.\n4. Pre-arranged Free Sparring (Yaksok Jayu Matsogi): A combination of pre-arranged and free sparring.\n5. Foot Technique Sparring (Bal Matsogi): Sparring using only foot techniques.",
        "content_ro": "Sparring-ul este aplicarea fizică a tehnicilor Taekwon-Do împotriva unui adversar sau a unor adversari în mișcare reală.\nSe împarte în:\n1. Sparring Pre-aranjat (Yaksok Matsogi): Mișcările sunt planificate în avans (cu 3 pași, 2 pași, 1 pas).\n2. Sparring Liber (Jayu Matsogi): Luptă liberă cu atacuri controlate.\n3. Sparring Model (Mobum Matsogi): Afișarea tehnicilor cu un partener în scopuri demonstrative.\n4. Sparring Liber Pre-aranjat (Yaksok Jayu Matsogi): O combinație de sparring pre-aranjat și liber.\n5. Sparring cu Tehnici de Picior (Bal Matsogi): Luptă folosind doar tehnici de picior."
    }
]


# ============================================================
# KOREAN TERMINOLOGY (extended from encyclopedia)
# ============================================================
TERMINOLOGY = [
    # Commands
    {"korean": "Cha-ryot", "hangul": "차렷", "en": "Attention", "ro": "Atenție", "category": "Commands"},
    {"korean": "Kyong-ye", "hangul": "경례", "en": "Bow", "ro": "Salut", "category": "Commands"},
    {"korean": "Joon-bi", "hangul": "준비", "en": "Ready", "ro": "Pregătit", "category": "Commands"},
    {"korean": "Si-jak", "hangul": "시작", "en": "Begin / Start", "ro": "Începe", "category": "Commands"},
    {"korean": "Goman", "hangul": "그만", "en": "Stop", "ro": "Stop", "category": "Commands"},
    {"korean": "Baro", "hangul": "바로", "en": "Return to ready", "ro": "Întoarcere la pregătit", "category": "Commands"},
    {"korean": "Swiyo", "hangul": "쉬어", "en": "Relax / At ease", "ro": "Relaxare", "category": "Commands"},
    {"korean": "Dwi-uro-dora", "hangul": "뒤로돌아", "en": "Turn around", "ro": "Întoarcere", "category": "Commands"},
    {"korean": "Hae-san", "hangul": "해산", "en": "Dismiss", "ro": "Sfârșit", "category": "Commands"},
    {"korean": "Kook-gi-e dae han kyung-ye", "hangul": "국기에 대한 경례", "en": "Bow to the flag", "ro": "Salut pentru drapel", "category": "Commands"},
    # Places & Things
    {"korean": "Dojang", "hangul": "도장", "en": "Training hall", "ro": "Sală de antrenament", "category": "Places & Things"},
    {"korean": "Dobok", "hangul": "도복", "en": "Uniform", "ro": "Uniformă", "category": "Places & Things"},
    {"korean": "Ti", "hangul": "띠", "en": "Belt", "ro": "Centură", "category": "Places & Things"},
    {"korean": "Kook-gi", "hangul": "국기", "en": "National flag", "ro": "Drapel național", "category": "Places & Things"},
    # Titles
    {"korean": "Boosabum", "hangul": "부사범", "en": "Assistant Instructor (1st-3rd Dan)", "ro": "Instructor Asistent (1-3 Dan)", "category": "Titles"},
    {"korean": "Sabum", "hangul": "사범", "en": "Instructor (4th-6th Dan)", "ro": "Instructor (4-6 Dan)", "category": "Titles"},
    {"korean": "Sahyun", "hangul": "사현", "en": "Master (7th-8th Dan)", "ro": "Maestru (7-8 Dan)", "category": "Titles"},
    {"korean": "Saseong", "hangul": "사성", "en": "Grand Master (9th Dan)", "ro": "Mare Maestru (9 Dan)", "category": "Titles"},
    # Techniques
    {"korean": "Jirugi", "hangul": "지르기", "en": "Punch / Thrust", "ro": "Pumn", "category": "Techniques"},
    {"korean": "Chagi", "hangul": "차기", "en": "Kick", "ro": "Lovitură de picior", "category": "Techniques"},
    {"korean": "Makgi", "hangul": "막기", "en": "Block", "ro": "Blocaj", "category": "Techniques"},
    {"korean": "Taerigi", "hangul": "때리기", "en": "Strike", "ro": "Lovitură", "category": "Techniques"},
    {"korean": "Tulgi", "hangul": "찌르기", "en": "Thrust (with fingers)", "ro": "Împungere", "category": "Techniques"},
    {"korean": "Sogi", "hangul": "서기", "en": "Stance", "ro": "Poziție", "category": "Techniques"},
    {"korean": "Tul", "hangul": "틀", "en": "Pattern", "ro": "Pattern", "category": "Techniques"},
    {"korean": "Matsogi", "hangul": "맞서기", "en": "Sparring", "ro": "Sparring", "category": "Techniques"},
    {"korean": "Hosin Sool", "hangul": "호신술", "en": "Self-defence", "ro": "Autoapărare", "category": "Techniques"},
    {"korean": "Kyok-pa", "hangul": "격파", "en": "Breaking", "ro": "Spargere", "category": "Techniques"},
    {"korean": "Kihap", "hangul": "기합", "en": "Spirit shout", "ro": "Strigăt de spirit", "category": "Techniques"},
    {"korean": "Dallyon", "hangul": "단련", "en": "Body conditioning", "ro": "Condiționarea corpului", "category": "Techniques"},
    # Directions
    {"korean": "Ap", "hangul": "앞", "en": "Front", "ro": "Față", "category": "Directions"},
    {"korean": "Yop", "hangul": "옆", "en": "Side", "ro": "Lateral", "category": "Directions"},
    {"korean": "Dwit", "hangul": "뒤", "en": "Back", "ro": "Spate", "category": "Directions"},
    {"korean": "Dollyo", "hangul": "돌려", "en": "Turning / Round", "ro": "Circular", "category": "Directions"},
    {"korean": "Najunde", "hangul": "낮은데", "en": "Low section", "ro": "Secțiune joasă", "category": "Directions"},
    {"korean": "Kaunde", "hangul": "가운데", "en": "Middle section", "ro": "Secțiune mijlocie", "category": "Directions"},
    {"korean": "Nopunde", "hangul": "높은데", "en": "High section", "ro": "Secțiune înaltă", "category": "Directions"},
    # Body parts
    {"korean": "Mori", "hangul": "머리", "en": "Head", "ro": "Cap", "category": "Body Parts"},
    {"korean": "Mok", "hangul": "목", "en": "Neck", "ro": "Gât", "category": "Body Parts"},
    {"korean": "Gasum", "hangul": "가슴", "en": "Chest", "ro": "Piept", "category": "Body Parts"},
    {"korean": "Bokboo", "hangul": "복부", "en": "Abdomen", "ro": "Abdomen", "category": "Body Parts"},
    {"korean": "Pal", "hangul": "팔", "en": "Arm", "ro": "Braț", "category": "Body Parts"},
    {"korean": "Dari", "hangul": "다리", "en": "Leg", "ro": "Picior", "category": "Body Parts"},
    {"korean": "Sonkal", "hangul": "손칼", "en": "Knife-hand", "ro": "Mâna-cuțit", "category": "Body Parts"},
    {"korean": "Joomuk", "hangul": "주먹", "en": "Fist", "ro": "Pumn", "category": "Body Parts"},
    {"korean": "Palkup", "hangul": "팔굽", "en": "Elbow", "ro": "Cot", "category": "Body Parts"},
    {"korean": "Mooreup", "hangul": "무릎", "en": "Knee", "ro": "Genunchi", "category": "Body Parts"},
    {"korean": "Kupso", "hangul": "급소", "en": "Vital spot", "ro": "Punct vital", "category": "Body Parts"},
    # Numbers
    {"korean": "Hana", "hangul": "하나", "en": "One", "ro": "Unu", "category": "Numbers"},
    {"korean": "Dool", "hangul": "둘", "en": "Two", "ro": "Doi", "category": "Numbers"},
    {"korean": "Set", "hangul": "셋", "en": "Three", "ro": "Trei", "category": "Numbers"},
    {"korean": "Net", "hangul": "넷", "en": "Four", "ro": "Patru", "category": "Numbers"},
    {"korean": "Dasot", "hangul": "다섯", "en": "Five", "ro": "Cinci", "category": "Numbers"},
    {"korean": "Yosot", "hangul": "여섯", "en": "Six", "ro": "Șase", "category": "Numbers"},
    {"korean": "Ilgop", "hangul": "일곱", "en": "Seven", "ro": "Șapte", "category": "Numbers"},
    {"korean": "Yodol", "hangul": "여덟", "en": "Eight", "ro": "Opt", "category": "Numbers"},
    {"korean": "Ahop", "hangul": "아홉", "en": "Nine", "ro": "Nouă", "category": "Numbers"},
    {"korean": "Yol", "hangul": "열", "en": "Ten", "ro": "Zece", "category": "Numbers"},
    # Theory of Power
    {"korean": "Him Ui Wolli", "hangul": "힘의 원리", "en": "Theory of Power", "ro": "Teoria Puterii", "category": "Theory"},
    {"korean": "Bandong Ryok", "hangul": "반동력", "en": "Reaction Force", "ro": "Forța de Reacție", "category": "Theory"},
    {"korean": "Jip Joong", "hangul": "집중", "en": "Concentration", "ro": "Concentrare", "category": "Theory"},
    {"korean": "Kyun Hyung", "hangul": "균형", "en": "Equilibrium", "ro": "Echilibru", "category": "Theory"},
    {"korean": "Hohup Jojul", "hangul": "호흡 조절", "en": "Breath Control", "ro": "Controlul Respirației", "category": "Theory"},
    {"korean": "Zilyang", "hangul": "질량", "en": "Mass", "ro": "Masa", "category": "Theory"},
    {"korean": "Sokdo", "hangul": "속도", "en": "Speed", "ro": "Viteza", "category": "Theory"},
    # Tenets
    {"korean": "Ye Ui", "hangul": "예의", "en": "Courtesy", "ro": "Curtoazie", "category": "Tenets"},
    {"korean": "Yom Chi", "hangul": "염치", "en": "Integrity", "ro": "Integritate", "category": "Tenets"},
    {"korean": "In Nae", "hangul": "인내", "en": "Perseverance", "ro": "Perseverență", "category": "Tenets"},
    {"korean": "Guk Gi", "hangul": "극기", "en": "Self-Control", "ro": "Autocontrol", "category": "Tenets"},
    {"korean": "Baekjul Boolgool", "hangul": "백절불굴", "en": "Indomitable Spirit", "ro": "Spirit Indomabil", "category": "Tenets"},
    # Attack Tools (Weapons of the body)
    {"korean": "Ap Kumchi", "hangul": "앞꿈치", "en": "Ball of the foot", "ro": "Pernița piciorului", "category": "Body Parts"},
    {"korean": "Balkal", "hangul": "발칼", "en": "Footsword (outer edge)", "ro": "Sabia piciorului (Cantul exterior)", "category": "Body Parts"},
    {"korean": "Dwi Kumchi", "hangul": "뒤꿈치", "en": "Heel", "ro": "Călcâi", "category": "Body Parts"},
    {"korean": "Balkut", "hangul": "발끝", "en": "Toes", "ro": "Vârfurile degetelor de la picioare", "category": "Body Parts"},
    {"korean": "Sonkal Dung", "hangul": "손칼등", "en": "Reverse knife-hand", "ro": "Muchiul palmei (Cantul interior)", "category": "Body Parts"},
    {"korean": "Sonkut", "hangul": "손끝", "en": "Fingertips", "ro": "Vârfurile degetelor", "category": "Body Parts"},
    {"korean": "Dung Joomuk", "hangul": "등주먹", "en": "Back fist", "ro": "Dosul pumnului", "category": "Body Parts"},
    {"korean": "Ap Joomuk", "hangul": "앞주먹", "en": "Forefist", "ro": "Partea frontală a pumnului", "category": "Body Parts"},
]


# ============================================================
# TECHNIQUES — stances, blocks, strikes, kicks
# ============================================================
TECHNIQUES = [
    # Stances
    {"id": "moa-sogi", "category": "Stances", "korean": "Moa Sogi", "en": "Close Stance", "ro": "Poziția Închisă", "description_en": "Stand with the feet together. It can be either full facing or side facing. Used in ready postures and bowing.", "description_ro": "Stai cu picioarele împreună. Poate fi față sau lateral. Folosită în pozițiile pregătit și salut."},
    {"id": "narani-sogi", "category": "Stances", "korean": "Narani Sogi", "en": "Parallel Stance", "ro": "Poziția Paralel", "description_en": "Spread the feet parallel to shoulder width. Keep the toes pointing toward the front. Full or side facing. The basic ready posture.", "description_ro": "Picioarele paralele, depărtate la lățimea umerilor, vârfurile spre față. Poziția pregătit de bază."},
    {"id": "annun-sogi", "category": "Stances", "korean": "Annun Sogi", "en": "Sitting Stance", "ro": "Poziția Așezat", "description_en": "Feet shoulder-width apart, parallel, weight evenly distributed. Used for power generation and punching exercises.", "description_ro": "Picioarele depărtate la lățimea umerilor, paralele, greutatea egal distribuită. Folosită pentru generarea puterii."},
    {"id": "gunnun-sogi", "category": "Stances", "korean": "Gunnun Sogi", "en": "Walking Stance", "ro": "Poziția Mers", "description_en": "Front foot points forward, back foot 25 degrees outward, 70% weight on front leg. A strong forward stance for attacking.", "description_ro": "Piciorul din față înainte, piciorul din spate la 25°, 70% greutate pe piciorul din față. Poziție puternică pentru atac."},
    {"id": "niunja-sogi", "category": "Stances", "korean": "Niunja Sogi", "en": "L-Stance", "ro": "Poziția L", "description_en": "Back foot at 90 degrees, front foot forward, 70% weight on back leg. Defensive stance.", "description_ro": "Piciorul din spate la 90°, piciorul din față înainte, 70% greutate pe piciorul din spate. Poziție defensivă."},
    {"id": "kyocha-sogi", "category": "Stances", "korean": "Kyocha Sogi", "en": "X-Stance", "ro": "Poziția X", "description_en": "One foot crosses over the other, used briefly during transitions or jumping techniques.", "description_ro": "Un picior trece peste celălalt; folosită în tranziții sau tehnici cu sărituri."},
    {"id": "goburyo-sogi", "category": "Stances", "korean": "Goburyo Sogi", "en": "Bending Ready Stance", "ro": "Poziția Pregătit Aplecat", "description_en": "One leg lifted with knee bent, used as ready posture for side kick.", "description_ro": "Un picior ridicat cu genunchiul îndoit; poziție pregătit pentru lovitură laterală."},
    {"id": "dwitbal-sogi", "category": "Stances", "korean": "Dwitbal Sogi", "en": "Rear Foot Stance", "ro": "Poziția Pe Piciorul din Spate", "description_en": "Most weight on the rear foot, front foot light — allows quick front kick or step.", "description_ro": "Cea mai mare parte din greutate pe piciorul din spate; permite lovitură rapidă sau pas."},
    # Blocks
    {"id": "najunde-makgi", "category": "Blocks", "korean": "Najunde Makgi", "en": "Low Block", "ro": "Blocaj Jos", "description_en": "Defends low-section attacks. The forearm sweeps downward across the body.", "description_ro": "Apără atacurile joase. Antebrațul mătură în jos peste corp."},
    {"id": "kaunde-makgi", "category": "Blocks", "korean": "Kaunde Makgi", "en": "Middle Block", "ro": "Blocaj Mijlociu", "description_en": "Defends middle-section attacks. Forearm blocks across the chest.", "description_ro": "Apără atacurile la mijloc. Antebrațul blochează peste piept."},
    {"id": "chookyo-makgi", "category": "Blocks", "korean": "Chookyo Makgi", "en": "Rising Block", "ro": "Blocaj Ridicare", "description_en": "Defends high overhead attacks. Forearm blocks upward.", "description_ro": "Apără atacurile sus. Antebrațul blochează în sus."},
    {"id": "sonkal-makgi", "category": "Blocks", "korean": "Sonkal Makgi", "en": "Knife-hand Block", "ro": "Blocaj Mâna-Cuțit", "description_en": "Block with the outer edge of the open hand.", "description_ro": "Blocaj cu marginea exterioară a mâinii deschise."},
    {"id": "palmok-daebi-makgi", "category": "Blocks", "korean": "Palmok Daebi Makgi", "en": "Forearm Guarding Block", "ro": "Blocaj de Gardă cu Antebrațul", "description_en": "Two-armed defensive guarding posture, common in L-stance.", "description_ro": "Poziție defensivă cu două brațe, comună în poziția L."},
    {"id": "bakuro-makgi", "category": "Blocks", "korean": "Bakuro Makgi", "en": "Outward Block", "ro": "Blocaj Spre Exterior", "description_en": "Forearm sweeps from the inside outward — deflects the attack to the side.", "description_ro": "Antebrațul mătură dinspre interior spre exterior — deviază atacul lateral."},
    {"id": "hechyo-makgi", "category": "Blocks", "korean": "Hechyo Makgi", "en": "Wedging Block", "ro": "Blocaj Pană", "description_en": "Both forearms wedge outward simultaneously to split a double attack.", "description_ro": "Ambele antebrațe împing spre exterior pentru a sparge un atac dublu."},
    # Strikes
    {"id": "ap-jirugi", "category": "Strikes", "korean": "Ap Jirugi", "en": "Front Punch", "ro": "Pumn Frontal", "description_en": "Straight punch delivered forward with the lead or rear hand.", "description_ro": "Pumn drept executat înainte cu mâna din față sau din spate."},
    {"id": "bandae-jirugi", "category": "Strikes", "korean": "Bandae Jirugi", "en": "Reverse Punch", "ro": "Pumn Invers", "description_en": "Punch with the rear hand opposite to the front leg.", "description_ro": "Pumn cu mâna din spate opusă piciorului din față."},
    {"id": "baro-jirugi", "category": "Strikes", "korean": "Baro Jirugi", "en": "Obverse Punch", "ro": "Pumn Direct", "description_en": "Punch with the same hand as the front leg.", "description_ro": "Pumn cu aceeași mână ca piciorul din față."},
    {"id": "doo-jirugi", "category": "Strikes", "korean": "Doo Jirugi", "en": "Double Punch", "ro": "Pumn Dublu", "description_en": "Two punches delivered consecutively with the same or opposite hands.", "description_ro": "Două lovituri consecutive cu aceeași mână sau cu mâna opusă."},
    {"id": "sonkal-taerigi", "category": "Strikes", "korean": "Sonkal Taerigi", "en": "Knife-hand Strike", "ro": "Lovitură Mâna-Cuțit", "description_en": "Strike with the outer edge of the open hand to the neck or jaw.", "description_ro": "Lovitură cu marginea exterioară a mâinii deschise spre gât sau maxilar."},
    {"id": "palkup-taerigi", "category": "Strikes", "korean": "Palkup Taerigi", "en": "Elbow Strike", "ro": "Lovitură cu Cotul", "description_en": "Powerful close-range strike with the elbow.", "description_ro": "Lovitură puternică pe distanță scurtă cu cotul."},
    {"id": "deung-joomuk-taerigi", "category": "Strikes", "korean": "Deung Joomuk Taerigi", "en": "Back Fist Strike", "ro": "Lovitură cu Dosul Pumnului", "description_en": "Strike with the back of the closed fist, often to the temple or face.", "description_ro": "Lovitură cu dosul pumnului închis, adesea spre tâmplă sau față."},
    # Kicks
    {"id": "ap-chagi", "category": "Kicks", "korean": "Ap Chagi", "en": "Front Snap Kick", "ro": "Lovitură Frontală Rapidă", "description_en": "Snapping kick delivered straight forward using the ball of the foot.", "description_ro": "Lovitură rapidă executată drept înainte cu perna piciorului."},
    {"id": "yop-chagi", "category": "Kicks", "korean": "Yop Chagi", "en": "Side Kick", "ro": "Lovitură Laterală", "description_en": "Powerful thrusting kick to the side using the footsword (sonkal).", "description_ro": "Lovitură puternică laterală folosind marginea piciorului (sonkal)."},
    {"id": "dollyo-chagi", "category": "Kicks", "korean": "Dollyo Chagi", "en": "Turning Kick", "ro": "Lovitură Circulară", "description_en": "Roundhouse kick using the ball of the foot or instep — hip rotation is key.", "description_ro": "Lovitură circulară cu perna piciorului sau dosul — rotația șoldului este cheia."},
    {"id": "dwit-chagi", "category": "Kicks", "korean": "Dwit Chagi", "en": "Back Kick", "ro": "Lovitură Spate", "description_en": "Powerful straight kick delivered backward — often used as counter.", "description_ro": "Lovitură puternică în spate — adesea folosită ca contraatac."},
    {"id": "bandal-chagi", "category": "Kicks", "korean": "Bandal Chagi", "en": "Crescent Kick", "ro": "Lovitură Semilună", "description_en": "Sweeping kick in an arc, inward or outward crescent.", "description_ro": "Lovitură măturătoare într-un arc, interioară sau exterioară."},
    {"id": "naeryo-chagi", "category": "Kicks", "korean": "Naeryo Chagi", "en": "Downward (Axe) Kick", "ro": "Lovitură Descendentă", "description_en": "Axe-like downward kick — the heel chops down on the target.", "description_ro": "Lovitură descendentă tip topor — călcâiul lovește în jos."},
    {"id": "twimyo-chagi", "category": "Kicks", "korean": "Twimyo Chagi", "en": "Flying Kick", "ro": "Lovitură Zburătoare", "description_en": "Jumping kick where both feet leave the ground.", "description_ro": "Lovitură cu sărituri în care ambele picioare părăsesc solul."},
    {"id": "bituro-chagi", "category": "Kicks", "korean": "Bituro Chagi", "en": "Twisting Kick", "ro": "Lovitură Răsucită", "description_en": "Kick performed with a twisting motion of the leg, attacking from an unusual angle.", "description_ro": "Lovitură executată cu o mișcare de răsucire a piciorului, atacând dintr-un unghi neobișnuit."},
]


# ============================================================
# BELT GRADING SYSTEM (verbatim significance from encyclopedia)
# ============================================================
GRADING_SYSTEM = [
    {"rank": "10th Kup", "color": "White", "color_ro": "Alb", "tul_required": "Saju Jirugi · Saju Makgi", "description_en": "Signifies innocence, as that of a beginning student who has no previous knowledge of Taekwon-Do.", "description_ro": "Semnifică inocența, ca cea a unui student începător care nu are cunoștințe anterioare despre Taekwon-Do."},
    {"rank": "9th Kup", "color": "White with Yellow stripe", "color_ro": "Alb cu dungă galbenă", "tul_required": "Chon-Ji", "description_en": "The student begins to take root.", "description_ro": "Studentul începe să prindă rădăcină."},
    {"rank": "8th Kup", "color": "Yellow", "color_ro": "Galben", "tul_required": "Dan-Gun", "description_en": "Signifies the Earth from which a plant sprouts and takes root as the Taekwon-Do foundation is being laid.", "description_ro": "Semnifică Pământul din care răsare și prinde rădăcină o plantă, în timp ce se așază fundația Taekwon-Do."},
    {"rank": "7th Kup", "color": "Yellow with Green stripe", "color_ro": "Galben cu dungă verde", "tul_required": "Do-San", "description_en": "Foundation is reinforced.", "description_ro": "Fundația este consolidată."},
    {"rank": "6th Kup", "color": "Green", "color_ro": "Verde", "tul_required": "Won-Hyo", "description_en": "Signifies the plant's growth as the Taekwon-Do skill begins to develop.", "description_ro": "Semnifică creșterea plantei pe măsură ce abilitatea Taekwon-Do începe să se dezvolte."},
    {"rank": "5th Kup", "color": "Green with Blue stripe", "color_ro": "Verde cu dungă albastră", "tul_required": "Yul-Gok", "description_en": "Continued development.", "description_ro": "Dezvoltare continuă."},
    {"rank": "4th Kup", "color": "Blue", "color_ro": "Albastru", "tul_required": "Joong-Gun", "description_en": "Signifies the Heaven, towards which the plant matures into a towering tree as training in Taekwon-Do progresses.", "description_ro": "Semnifică Cerul, spre care planta se maturizează într-un copac înalt, pe măsură ce antrenamentul progresează."},
    {"rank": "3rd Kup", "color": "Blue with Red stripe", "color_ro": "Albastru cu dungă roșie", "tul_required": "Toi-Gye", "description_en": "Maturity approaching.", "description_ro": "Apropierea maturității."},
    {"rank": "2nd Kup", "color": "Red", "color_ro": "Roșu", "tul_required": "Hwa-Rang", "description_en": "Signifies danger, cautioning the student to exercise control and warning the opponent to stay away.", "description_ro": "Semnifică pericolul, avertizând studentul să exercite control și avertizându-l pe adversar să stea departe."},
    {"rank": "1st Kup", "color": "Red with Black stripe", "color_ro": "Roșu cu dungă neagră", "tul_required": "Choong-Moo", "description_en": "Final stage before black belt.", "description_ro": "Etapa finală înainte de centura neagră."},
    {"rank": "1st Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Kwang-Gae · Po-Eun · Ge-Baek", "description_en": "Opposite of white. Signifies the maturity and proficiency in Taekwon-Do. Indicates the wearer's imperviousness to darkness and fear.", "description_ro": "Opusul albului. Semnifică maturitatea și competența. Indică imunitatea purtătorului față de întuneric și frică."},
    {"rank": "2nd Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Eui-Am · Choong-Jang · Juche", "description_en": "Continued mastery — novice stage of black belt.", "description_ro": "Stăpânire continuă — etapă de începător a centurii negre."},
    {"rank": "3rd Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Sam-Il · Yoo-Sin · Choi-Yong", "description_en": "End of novice stage. Eligible for Boosabum (Assistant Instructor).", "description_ro": "Sfârșitul etapei de începător. Eligibil pentru Boosabum (Instructor Asistent)."},
    {"rank": "4th Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Yon-Gae · Ul-Ji", "description_en": "Crossing the threshold of puberty into the expert class. Sabum (Instructor) certification.", "description_ro": "Trecerea pragului pubertății către clasa experților. Certificare Sabum (Instructor)."},
    {"rank": "5th Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Moon-Moo · So-San", "description_en": "Senior expert.", "description_ro": "Expert senior."},
    {"rank": "6th Dan", "color": "Black", "color_ro": "Negru", "tul_required": "All previous patterns mastered", "description_en": "Approaching mastery.", "description_ro": "Apropierea maturității depline."},
    {"rank": "7th Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Se-Jong", "description_en": "Sahyun (Master). Member of the elite who fully understand all the particulars of Taekwon-Do, mental and physical.", "description_ro": "Sahyun (Maestru). Membru al elitei care înțelege toate aspectele Taekwon-Do, mentale și fizice."},
    {"rank": "8th Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Tong-Il", "description_en": "Senior Master.", "description_ro": "Maestru Senior."},
    {"rank": "9th Dan", "color": "Black", "color_ro": "Negru", "tul_required": "Mastery of all 24 patterns", "description_en": "Saseong — Grand Master. The highest rank in Taekwon-Do (3 × 3, the highest of the high).", "description_ro": "Saseong — Mare Maestru. Cel mai înalt rang în Taekwon-Do (3 × 3, cel mai înalt dintre cele mai înalte)."},
]


# ============================================================
# QUIZ — questions sourced directly from the Encyclopedia
# ============================================================
QUIZ_QUESTIONS = [
    {"id": "q1", "question_en": "Who is the founder of Taekwon-Do?", "question_ro": "Cine este fondatorul Taekwon-Do?", "options_en": ["Bruce Lee", "General Choi Hong Hi", "Mas Oyama", "Gichin Funakoshi"], "options_ro": ["Bruce Lee", "Generalul Choi Hong Hi", "Mas Oyama", "Gichin Funakoshi"], "correct": 1, "category": "History"},
    {"id": "q2", "question_en": "On what date was Taekwon-Do officially named?", "question_ro": "Pe ce dată a fost numit oficial Taekwon-Do?", "options_en": ["April 11, 1955", "March 22, 1966", "September 9, 1945", "June 25, 1950"], "options_ro": ["11 aprilie 1955", "22 martie 1966", "9 septembrie 1945", "25 iunie 1950"], "correct": 0, "category": "History"},
    {"id": "q3", "question_en": "When was the ITF founded?", "question_ro": "Când a fost fondată ITF?", "options_en": ["April 11, 1955", "March 22, 1966", "1972", "1980"], "options_ro": ["11 aprilie 1955", "22 martie 1966", "1972", "1980"], "correct": 1, "category": "History"},
    {"id": "q4", "question_en": "How many tuls (patterns) are there in ITF Taekwon-Do?", "question_ro": "Câte tul-uri (pattern-uri) există în ITF Taekwon-Do?", "options_en": ["20", "22", "24", "26"], "options_ro": ["20", "22", "24", "26"], "correct": 2, "category": "Patterns"},
    {"id": "q5", "question_en": "Why are there 24 patterns?", "question_ro": "De ce sunt 24 de pattern-uri?", "options_en": ["24 letters of Hangul", "24 hours = one day = a lifetime", "24 founders of ITF", "24 Korean provinces"], "options_ro": ["24 de litere Hangul", "24 de ore = o zi = o viață", "24 de fondatori ai ITF", "24 de provincii coreene"], "correct": 1, "category": "Patterns"},
    {"id": "q6", "question_en": "What does Chon-Ji mean?", "question_ro": "Ce înseamnă Chon-Ji?", "options_en": ["Sun and Moon", "The Heaven and the Earth", "Fire and Water", "Wind and Storm"], "options_ro": ["Soare și Lună", "Cerul și Pământul", "Foc și Apă", "Vânt și Furtună"], "correct": 1, "category": "Patterns"},
    {"id": "q7", "question_en": "How many movements are in Dan-Gun?", "question_ro": "Câte mișcări sunt în Dan-Gun?", "options_en": ["19", "21", "24", "28"], "options_ro": ["19", "21", "24", "28"], "correct": 1, "category": "Patterns"},
    {"id": "q8", "question_en": "Who is Do-San named after?", "question_ro": "După cine este numit Do-San?", "options_en": ["A king", "Patriot Ahn Chang-Ho", "A monk", "A general"], "options_ro": ["Un rege", "Patriotul Ahn Chang-Ho", "Un călugăr", "Un general"], "correct": 1, "category": "Patterns"},
    {"id": "q9", "question_en": "Why does Choong-Moo end with a left-hand attack?", "question_ro": "De ce se termină Choong-Moo cu un atac cu mâna stângă?", "options_en": ["For symmetry", "Symbolizes Yi Soon-Sin's regrettable death", "For balance", "It was an error"], "options_ro": ["Pentru simetrie", "Simbolizează moartea regretabilă a lui Yi Soon-Sin", "Pentru echilibru", "A fost o eroare"], "correct": 1, "category": "Patterns"},
    {"id": "q10", "question_en": "Which pattern represents 24 letters of the Korean alphabet?", "question_ro": "Care pattern reprezintă cele 24 de litere ale alfabetului coreean?", "options_en": ["Sam-Il", "Se-Jong", "Tong-Il", "Moon-Moo"], "options_ro": ["Sam-Il", "Se-Jong", "Tong-Il", "Moon-Moo"], "correct": 1, "category": "Patterns"},
    {"id": "q11", "question_en": "Which of these is NOT one of the Five Tenets?", "question_ro": "Care NU este unul dintre Cele Cinci Principii?", "options_en": ["Courtesy", "Integrity", "Wisdom", "Self-Control"], "options_ro": ["Curtoazie", "Integritate", "Înțelepciune", "Autocontrol"], "correct": 2, "category": "Philosophy"},
    {"id": "q12", "question_en": "What is the Korean term for Indomitable Spirit?", "question_ro": "Care este termenul coreean pentru Spirit Indomabil?", "options_en": ["Ye Ui", "Yom Chi", "In Nae", "Baekjul Boolgool"], "options_ro": ["Ye Ui", "Yom Chi", "In Nae", "Baekjul Boolgool"], "correct": 3, "category": "Philosophy"},
    {"id": "q13", "question_en": "How many components are in the Theory of Power?", "question_ro": "Câte componente are Teoria Puterii?", "options_en": ["4", "5", "6", "7"], "options_ro": ["4", "5", "6", "7"], "correct": 2, "category": "Theory"},
    {"id": "q14", "question_en": "Korean term for Reaction Force?", "question_ro": "Termenul coreean pentru Forța de Reacție?", "options_en": ["Bandong Ryok", "Jip Joong", "Sokdo", "Zilyang"], "options_ro": ["Bandong Ryok", "Jip Joong", "Sokdo", "Zilyang"], "correct": 0, "category": "Theory"},
    {"id": "q15", "question_en": "If speed is tripled, power is multiplied by:", "question_ro": "Dacă viteza se triplează, puterea se înmulțește cu:", "options_en": ["3", "6", "9", "12"], "options_ro": ["3", "6", "9", "12"], "correct": 2, "category": "Theory"},
    {"id": "q16", "question_en": "The formula for power in Taekwon-Do is:", "question_ro": "Formula pentru putere în Taekwon-Do este:", "options_en": ["P = m × v", "P = ½ m v²", "P = m a²", "P = m + v"], "options_ro": ["P = m × v", "P = ½ m v²", "P = m a²", "P = m + v"], "correct": 1, "category": "Theory"},
    {"id": "q17", "question_en": "What does 'Charyot' mean?", "question_ro": "Ce înseamnă 'Charyot'?", "options_en": ["Begin", "Stop", "Attention", "Bow"], "options_ro": ["Începe", "Stop", "Atenție", "Salut"], "correct": 2, "category": "Terminology"},
    {"id": "q18", "question_en": "What is 'Sabum'?", "question_ro": "Ce înseamnă 'Sabum'?", "options_en": ["Black belt", "Instructor (4th-6th Dan)", "Student", "Master"], "options_ro": ["Centură neagră", "Instructor (4-6 Dan)", "Student", "Maestru"], "correct": 1, "category": "Terminology"},
    {"id": "q19", "question_en": "Korean for 'kick'?", "question_ro": "Coreeana pentru 'lovitură de picior'?", "options_en": ["Jirugi", "Chagi", "Makgi", "Taerigi"], "options_ro": ["Jirugi", "Chagi", "Makgi", "Taerigi"], "correct": 1, "category": "Terminology"},
    {"id": "q20", "question_en": "Which kick is 'Yop Chagi'?", "question_ro": "Care lovitură este 'Yop Chagi'?", "options_en": ["Front", "Side", "Turning", "Back"], "options_ro": ["Frontală", "Laterală", "Circulară", "Spate"], "correct": 1, "category": "Techniques"},
    {"id": "q21", "question_en": "What does 'Tul' mean?", "question_ro": "Ce înseamnă 'Tul'?", "options_en": ["Sparring", "Pattern", "Stance", "Block"], "options_ro": ["Sparring", "Pattern", "Poziție", "Blocaj"], "correct": 1, "category": "Terminology"},
    {"id": "q22", "question_en": "What color belt is required to learn Chon-Ji?", "question_ro": "Ce culoare de centură este necesară pentru Chon-Ji?", "options_en": ["White", "Yellow", "Green", "Blue"], "options_ro": ["Alb", "Galben", "Verde", "Albastru"], "correct": 1, "category": "Grading"},
    {"id": "q23", "question_en": "Yellow belt signifies:", "question_ro": "Centura galbenă semnifică:", "options_en": ["The sun", "The Earth", "Innocence", "Danger"], "options_ro": ["Soarele", "Pământul", "Inocența", "Pericolul"], "correct": 1, "category": "Grading"},
    {"id": "q24", "question_en": "Blue belt signifies:", "question_ro": "Centura albastră semnifică:", "options_en": ["Water", "The Heaven", "Sky", "Maturity"], "options_ro": ["Apa", "Cerul", "Cerul senin", "Maturitatea"], "correct": 1, "category": "Grading"},
    {"id": "q25", "question_en": "Red belt signifies:", "question_ro": "Centura roșie semnifică:", "options_en": ["Fire", "Danger — control", "Anger", "Strength"], "options_ro": ["Focul", "Pericol — control", "Furie", "Forță"], "correct": 1, "category": "Grading"},
    {"id": "q26", "question_en": "Black belt signifies (opposite of white):", "question_ro": "Centura neagră (opusul albului) semnifică:", "options_en": ["Death", "Maturity & imperviousness to fear", "Power only", "End of journey"], "options_ro": ["Moartea", "Maturitate și imunitate la frică", "Doar putere", "Sfârșitul călătoriei"], "correct": 1, "category": "Grading"},
    {"id": "q27", "question_en": "What is the highest rank in Taekwon-Do?", "question_ro": "Care este cel mai înalt rang în Taekwon-Do?", "options_en": ["7th Dan", "8th Dan", "9th Dan", "10th Dan"], "options_ro": ["7 Dan", "8 Dan", "9 Dan", "10 Dan"], "correct": 2, "category": "Grading"},
    {"id": "q28", "question_en": "Why is 9th Dan the highest? (encyclopedia answer)", "question_ro": "De ce este 9 Dan cel mai înalt? (răspuns din enciclopedie)", "options_en": ["It is round", "Because 9 = 3 × 3, and 3 is the most esteemed Oriental number", "Random choice", "Symbolic of years of training"], "options_ro": ["Este rotund", "Deoarece 9 = 3 × 3, iar 3 este cel mai prețuit număr oriental", "Alegere aleatorie", "Simbol al anilor de antrenament"], "correct": 1, "category": "Grading"},
    {"id": "q29", "question_en": "How is the belt wrapped (since July 1985)?", "question_ro": "Cum se înfășoară centura (din iulie 1985)?", "options_en": ["Twice around", "Once around (1)", "Three times", "Tied at the side"], "options_ro": ["De două ori în jur", "O singură dată în jur (1)", "De trei ori", "Legată lateral"], "correct": 1, "category": "Grading"},
    {"id": "q30", "question_en": "Which translation of 'Tae' is correct?", "question_ro": "Care traducere a 'Tae' este corectă?", "options_en": ["Hand", "Jumping/Flying foot kick", "Way", "Spirit"], "options_ro": ["Mână", "Lovitură cu piciorul în salt/zbor", "Cale", "Spirit"], "correct": 1, "category": "Theory"},
    {"id": "q31", "question_en": "What does 'Do' in Taekwon-Do literally mean?", "question_ro": "Ce înseamnă literal 'Do' în Taekwon-Do?", "options_en": ["Strength", "The art / way", "Kick", "Sport"], "options_ro": ["Forță", "Arta / calea", "Lovitură", "Sport"], "correct": 1, "category": "Theory"},
    {"id": "q32", "question_en": "Approximate normal human reflex time per encyclopedia experiment:", "question_ro": "Timpul normal de reflex uman conform experimentului din enciclopedie:", "options_en": ["1/10 sec", "2/10 sec", "1/2 sec", "1 sec"], "options_ro": ["1/10 sec", "2/10 sec", "1/2 sec", "1 sec"], "correct": 1, "category": "Theory"},
    {"id": "q33", "question_en": "How many movements in Yul-Gok and why?", "question_ro": "Câte mișcări are Yul-Gok și de ce?", "options_en": ["38 — birthplace at 38° latitude", "29 — division number", "33 — patriots", "24 — letters"], "options_ro": ["38 — locul nașterii la 38° latitudine", "29 — numărul diviziei", "33 — patrioți", "24 — litere"], "correct": 0, "category": "Patterns"},
    {"id": "q34", "question_en": "Hwa-Rang's 29 movements refer to:", "question_ro": "Cele 29 de mișcări din Hwa-Rang se referă la:", "options_en": ["Age of founder", "29th Infantry Division", "Year 1929", "29 warriors"], "options_ro": ["Vârsta fondatorului", "Divizia 29 de Infanterie", "Anul 1929", "29 de războinici"], "correct": 1, "category": "Patterns"},
    {"id": "q35", "question_en": "When does Sam-Il commemorate?", "question_ro": "Ce comemorează Sam-Il?", "options_en": ["Korean War", "March 1, 1919 independence movement", "Founding of ITF", "Korean unification"], "options_ro": ["Războiul Coreean", "Mișcarea de independență din 1 martie 1919", "Fondarea ITF", "Unificarea Coreei"], "correct": 1, "category": "Patterns"},
    {"id": "q36", "question_en": "What is the Korean term for Free Sparring?", "question_ro": "Care este termenul coreean pentru Sparring Liber?", "options_en": ["Yaksok Matsogi", "Jayu Matsogi", "Mobum Matsogi", "Bal Matsogi"], "options_ro": ["Yaksok Matsogi", "Jayu Matsogi", "Mobum Matsogi", "Bal Matsogi"], "correct": 1, "category": "Terminology"},
    {"id": "q37", "question_en": "How many training secrets did General Choi highlight?", "question_ro": "Câte secrete de antrenament a evidențiat Generalul Choi?", "options_en": ["5", "6", "8", "10"], "options_ro": ["5", "6", "8", "10"], "correct": 2, "category": "Theory"},
    {"id": "q38", "question_en": "In the Sine Wave motion, what are the three phases?", "question_ro": "În mișcarea Sine Wave, care sunt cele trei faze?", "options_en": ["Up - Down - Up", "Down - Up - Down", "Left - Right - Forward", "Down - Forward - Down"], "options_ro": ["Sus - Jos - Sus", "Jos - Sus - Jos", "Stânga - Dreapta - Față", "Jos - Față - Jos"], "correct": 1, "category": "Theory"},
    {"id": "q39", "question_en": "What is the 'Footsword' in Korean?", "question_ro": "Cum se spune 'Sabia piciorului' în coreeană?", "options_en": ["Balkal", "Ap Kumchi", "Dwi Kumchi", "Moorup"], "options_ro": ["Balkal", "Ap Kumchi", "Dwi Kumchi", "Moorup"], "correct": 0, "category": "Terminology"},
    {"id": "q40", "question_en": "Which section of the body is 'Kaunde'?", "question_ro": "Care secțiune a corpului este 'Kaunde'?", "options_en": ["High", "Middle", "Low", "Back"], "options_ro": ["Înaltă", "Mijlocie", "Joasă", "Spate"], "correct": 1, "category": "Terminology"},
]
